repoURL: https://github.com/treddy08/model-as-a-service.git
targetRevision: main

maasApi:
  clusterDomain: apps.cluster-7d86.7d86.sandbox246.opentlc.com

redhat-connectivity-link:
  operator:
    channel: stable
    installPlanApproval: Automatic
    startingCSV: rhcl-operator.v1.2.0
