apiVersion: v1
kind: Secret
metadata:
  name: api-key-test-user
  namespace: maas-api-keys
  labels:
    authorino.kuadrant.io/managed-by: authorino
  annotations:
    user.authorino.kuadrant.io/userid: "test-user"
    sync.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  api_key: {{ randAlphaNum 20 | quote }}
