apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authorino-secret-reader-binding
  namespace: maas-api-keys
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: authorino-authorino
    namespace: openshift-operators
roleRef:
  kind: Role
  name: authorino-secret-reader
  apiGroup: rbac.authorization.k8s.io