apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant-instance
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec: {}
