apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.maasUser.username }}-llminferenceservice-access-binding
  namespace: llm
subjects:
  - kind: User
    name: {{ .Values.maasUser.username }}n
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: llminferenceservice-access
  apiGroup: rbac.authorization.k8s.io
